### ISSUE TITLE
Fedora instructions fail

### ISSUE THREAD

**Issue by amilopowers** [canonical-websites/snapcraft.io-static-pages#278]
## Summary

I followed the Fedora guide and when I enter `sudo dnf install snapd` I get: `Failed to synchronize cache for repo 'zyga-snapcore'`

## Process

Guide is here: https://snapcraft.io/docs/core/install

Entered:
`sudo dnf copr enable zyga/snapcore
sudo dnf install snapd`

## Current and expected result
got: `Failed to synchronize cache for repo 'zyga-snapcore'`
Should: Install snapd

**Comment by amilopowers** [comment]
I work with Fedora 25 and GNOME 3.22.2 btw.

**Comment by Conan-Kudo** [comment]
@amilopowers This should be fixed now in new https://snapcraft.io/docs/core/install-fedora

**Comment by amilopowers** [comment]
I use Antergos now so I can't verify.

**Comment by matthewpaulthomas** [comment]
Duplicate of #284, where the reporter was able to verify the fix.
