### ISSUE TITLE
Documentation Bug: Snapd install for Fedora 25

### ISSUE THREAD

**Issue by eriknelson** [canonical-websites/snapcraft.io-static-pages#284]
## Summary

zyga/snapcore doesn't support Fedora 25. I'm assuming that's a bug that has to get filed against the copr repo, so I'm mainly looking for the install page to list supported versions (or those that are unsupported). It's not obvious from the error message for new users that the root problem is Fedora 25.

## Process

On a Fedora 25 machine:

```
sudo dnf copr enable zyga/snapcore
# sudo dnf install snapd
Failed to synchronize cache for repo 'zyga-snapcore', disabling.
Last metadata expiration check: 0:38:34 ago on Wed Feb 22 07:41:16 2017.
No package snapd available.
Error: Unable to find a match.
```

## Current and expected result

**Current**: Snapcraft install page doesn't mention anything about Fedora 25 non-support.

**Expected**: Some kind of note specifying Fedora 25 is not supported (obviously removed when copr is updated).

**Comment by Conan-Kudo** [comment]
@eriknelson This should be fixed now in new https://snapcraft.io/docs/core/install-fedora

**Comment by eriknelson** [comment]
@Conan-Kudo Confirmed I can now install! Thank you, it's probably appropriate to close this now.

**Comment by matthewpaulthomas** [comment]
@eriknelson A belated thanks for verifying the fix.
