### ISSUE TITLE
FAQ page is differently branded

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io-static-pages#290]
The FAQ page takes you off to https://developer.ubuntu.com/en/snappy/support/faq/. This is both jarring and not in line with snapcraft being distribution neutral.

**Comment by pmahnke** [comment]
@evandandrea that's because developer.ubuntu.com is fully ubuntu branded.  If that is the only page on dev that is wrong, then we should just move it to snapcraft.io

**Comment by evandandrea** [comment]
Correct and agreed, we should move it to snapcraft.io

**Comment by matthewpaulthomas** [comment]
Neither Google nor I can find any page on snapcraft.io with a “FAQ” link (good!), and the cited URL is a 404. So this looks long fixed.
