### ISSUE TITLE
Text over-runs logos at top of page - Win10/IE11

### ISSUE THREAD

**Issue by popey** [canonical-websites/snapcraft.io-static-pages#295]
## Summary

Text at the top of the page over-runs the logos on the right

## Process

Visit snapcraft.io in IE11 on Windows 10

## Current and expected result

Text over-ran
Expected it not to

## Screenshot

![screenshot 8](https://cloud.githubusercontent.com/assets/1841272/24397941/a5c1c9e2-139f-11e7-9b89-0cb609d3cc85.png)

**Comment by caldav** [comment]
The latest version of the homepage layout works around this issue.
