### ISSUE TITLE
Mention user testing in the footer

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io-static-pages#300]
Next to "Report a bug on this site" can we have:

"Help us improve the platform, [participate in user testing](https://docs.google.com/forms/d/e/1FAIpQLSfCbGjGlCHCx3CdjH6Ls2nPd37nWFzlBoVXq1hAC9V9cYz2AA/viewform)"

**Comment by caldav** [comment]
@evandandrea is this still relevant?

**Comment by evandandrea** [comment]
Nope :)
