### ISSUE TITLE
Manjaro supports snaps now

### ISSUE THREAD

**Issue by philmmanjaro** [canonical-websites/snapcraft.io-static-pages#387]
## Summary

Manjaro Linux supports now basic snap support. We already have [uploaded](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170918/012778.html) our first working packages to our **unstable** branches. A distribution logo can be found [here](https://github.com/manjaro/artwork-logo).

## Process

You can install **snapd** currently this way:

```
sudo pacman-mirrors -gb unstable
sudo pacman -Sy snapd
sudo systemctl enable --now snapd.socket
```

## Screenshot

<img src="https://pbs.twimg.com/media/DKVgn61XoAEyBdK.png">

**Comment by philmmanjaro** [comment]
It can be installed now from all branches via:

```
sudo pacman -Sy snapd
sudo systemctl enable --now snapd.socket
```

**Comment by caldav** [comment]
See https://github.com/CanonicalLtd/snappy-docs/pull/128 for install steps PR
