### ISSUE TITLE
Seeing different version of Snapcraft on different browsers for different users

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/snapcraft.io-static-pages#395]
## Summary
- Lubo sees the old version of snapcraft on chrome
- Greg sees the old version on chrome (incognito) and safari
- Greg sees the new version on chrome
- Karl sees the new version on Chromium and Firefox 

Karl thinks it may be something to do with the 'squid bouncer'

### Old version
![snapcraft - chrome incognito](https://user-images.githubusercontent.com/23459065/31554492-a78067d8-b035-11e7-91eb-b847e52bf5d3.png)

### New version
<img width="1157" alt="snapcraft - chrome" src="https://user-images.githubusercontent.com/23459065/31554506-b4d1e0a6-b035-11e7-9fe5-035aa11a7d90.png">

### A squid
![image](https://user-images.githubusercontent.com/23459065/31554572-dea2104a-b035-11e7-9606-e637226fa3d9.png)

**Comment by caldav** [comment]
A/B testing going on. 2 actually, one to display/hide the wall of content beneath the logos grid, the other to change the order and style of CTAs at the top.
