### ISSUE TITLE
Open 

### ISSUE THREAD

**Issue by AbuOmair** [canonical-websites/snapcraft.io-static-pages#396]
## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by AbuOmair** [comment]
Opening the new app

**Comment by matthewpaulthomas** [comment]
@AbuOmair This is the second uninformative report that you have made here (after #394). Please stop.

**Comment by AbuOmair** [comment]
Stop
